on: [push]

jobs:
  hello_world_job_good:
    runs-on: ubuntu-latest
    name: A job to say hello (good)
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions/greeter-good
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
  hello_world_job_not_good:
    runs-on: ubuntu-latest
    name: A job to say hello (not good)
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions/greeter-not-good
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
